[0m15:10:56.187763 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ee09ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ec3c0fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ec3c0eb0>]}


============================== 15:10:56.191745 | 5bba3836-c569-4038-af46-114495f749a9 ==============================
[0m15:10:56.191745 [info ] [MainThread]: Running with dbt=1.6.6
[0m15:10:56.192293 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/caiouehara/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:11:01.322894 [debug] [MainThread]: Starter project path: /home/caiouehara/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m15:11:01.326188 [info ] [MainThread]: 
Your new dbt project "dbt_adatech" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:11:01.326787 [info ] [MainThread]: Setting up your profile.
[0m15:11:02.385445 [debug] [MainThread]: Command `dbt init` succeeded at 15:11:02.385283 after 6.20 seconds
[0m15:11:02.385846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ee09ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ec3c1150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93ec3c11e0>]}
[0m15:11:02.386209 [debug] [MainThread]: Flushing usage events
[0m17:31:35.455698 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67feec1b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67ff482de0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67ff4c4bc0>]}


============================== 17:31:35.459204 | c6f7d12d-b85c-4537-9ca7-5f87fd3f8e4a ==============================
[0m17:31:35.459204 [info ] [MainThread]: Running with dbt=1.6.6
[0m17:31:35.459773 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/caiouehara/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:31:35.460283 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/caiouehara/code-workspace/ADATech-AnalyticsEngineering/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:31:35.460876 [debug] [MainThread]: Command `dbt run` failed at 17:31:35.460745 after 0.01 seconds
[0m17:31:35.461225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67ff31cd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67ff564e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f67ff112e10>]}
[0m17:31:35.461543 [debug] [MainThread]: Flushing usage events
[0m17:32:21.408783 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493c5c7620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493d75b560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493c9e6660>]}


============================== 17:32:21.413007 | 20eb775b-51b0-404e-900d-47d936e6a14d ==============================
[0m17:32:21.413007 [info ] [MainThread]: Running with dbt=1.6.6
[0m17:32:21.413919 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/caiouehara/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt list', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:32:21.414609 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/caiouehara/code-workspace/ADATech-AnalyticsEngineering/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:32:21.415448 [debug] [MainThread]: Command `dbt list` failed at 17:32:21.415282 after 0.02 seconds
[0m17:32:21.415963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493c939520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493c816300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f493cbf4e30>]}
[0m17:32:21.416492 [debug] [MainThread]: Flushing usage events
[0m17:32:26.776568 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f71839993a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7183c8b8c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f71849acb60>]}


============================== 17:32:26.780564 | 5002c009-c67b-4d40-b828-25fdb28339bb ==============================
[0m17:32:26.780564 [info ] [MainThread]: Running with dbt=1.6.6
[0m17:32:26.781351 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/caiouehara/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:32:26.782678 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/caiouehara/code-workspace/ADATech-AnalyticsEngineering/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:32:26.783885 [debug] [MainThread]: Command `dbt run` failed at 17:32:26.783698 after 0.02 seconds
[0m17:32:26.784455 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f71874bd460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7183f25af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7183ee06e0>]}
[0m17:32:26.784967 [debug] [MainThread]: Flushing usage events
